In [236]:
import numpy as np
import pandas as pd
pd.__version__

'2.2.3'

## 1. Create a Pandas DataFrame from a dictionary
<pre>Given Input:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Salary': [50000, 70000, 90000, 110000]}

Desired Output:
    Name	 Age	Salary
0	Alice	 25	 50000
1	Bob	   30	 70000
2	Charlie   35	 90000
3	David	 40	 110000
</pre>

In [237]:
dataVoV = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Salary': [50000, 70000, 90000, 110000]}
AaaDFaaA= pd.DataFrame(data=dataVoV)

print(AaaDFaaA,"\nType(dataVoV):", type(dataVoV))

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   70000
2  Charlie   35   90000
3    David   40  110000
Type(dataVoV): <class 'dict'>

## 2. Load a CSV file into a Pandas DataFrame
Given iris CSV dataset: iris.csv

In [238]:
Df_iris=pd.read_csv("iris.csv")

## 3. View the first, last and sample of 2 rows of a DataFrame
Given the iris df above

In [239]:
Df_iris.head(2)

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa

In [240]:
Df_iris.tail(2)

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [241]:
Df_iris.sample(2)

    SepalLength  SepalWidth  PetalLength  PetalWidth             Name
65          6.7         3.1          4.4         1.4  Iris-versicolor
71          6.1         2.8          4.0         1.3  Iris-versicolor

## 4. Get basic information and descriptive statistics about a DataFrame

In [242]:
# info
Df_iris.info

<bound method DataFrame.info of      SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]>

In [243]:

Df_iris.value_counts()

SepalLength  SepalWidth  PetalLength  PetalWidth  Name
4.9          3.1         1.5          0.1         Iris-setosa        3
5.8          2.7         5.1          1.9         Iris-virginica     2
             4.0         1.2          0.2         Iris-setosa        1
5.9          3.0         4.2          1.5         Iris-versicolor    1
6.2          3.4         5.4          2.3         Iris-virginica     1
                                                                    ..
5.5          2.3         4.0          1.3         Iris-versicolor    1
             2.4         3.7          1.0         Iris-versicolor    1
                         3.8          1.1         Iris-versicolor    1
             2.5         4.0          1.3         Iris-versicolor    1
7.9          3.8         6.4          2.0         Iris-virginica     1
Name: count, Length: 147, dtype: int64

In [244]:
Df_iris.describe(include='O')

'''

上に示したように、describe()はデフォルトでは数値データ（int型やfloat型など）の基本統計量を表示しますが、引数にinclude='O'（大文字のオーです）を指定することで、オブジェクトデータ（str型など）に関する情報を表示できます。このとき表示されるのは、上から、データ数（count）、重複を排除したデータ数（unique）、最も多く含まれるデータ（top）、そのデータが含まれる個数（freq）です。
https://qiita.com/0NE_shoT_/items/bf700662b2c36aee0f8e
data.describe(include='O')
describe(include=['O']).jpg
さらに、引数にinclude='all'を指定することで、数値データとオブジェクトデータに関する情報を合わせて表示することができます

'''

"\n\n上に示したように、describe()はデフォルトでは数値データ（int型やfloat型など）の基本統計量を表示しますが、引数にinclude='O'（大文字のオーです）を指定することで、オブジェクトデータ（str型など）に関する情報を表示できます。このとき表示されるのは、上から、データ数（count）、重複を排除したデータ数（unique）、最も多く含まれるデータ（top）、そのデータが含まれる個数（freq）です。\nhttps://qiita.com/0NE_shoT_/items/bf700662b2c36aee0f8e\ndata.describe(include='O')\ndescribe(include=['O']).jpg\nさらに、引数にinclude='all'を指定することで、数値データとオブジェクトデータに関する情報を合わせて表示することができます\n\n"

In [245]:
Df_iris.Name.value_counts().values

# df.groupby('colA')['colA'].count()  https://segmentfault.com/q/1010000043270370

array([50, 50, 50], dtype=int64)

In [246]:
Df_iris

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [247]:
Df_iris.groupby('SepalLength')[['SepalLength','PetalLength','PetalWidth','Name']]

#.value_counts().values

#SepalWidth  PetalLength  PetalWidth  Name

In [248]:
Df_iris.groupby('SepalLength')[['PetalLength','PetalWidth','Name']].sum().reset_index()

,SepalLength,PetalLength,PetalWidth,Name
0,4.3,1.1,0.1,Iris-setosa
1,4.4,4.0,0.6,Iris-setosaIris-setosaIris-setosa
2,4.5,1.3,0.3,Iris-setosa
3,4.6,5.3,0.9,Iris-setosaIris-setosaIris-setosaIris-setosa
4,4.7,2.9,0.4,Iris-setosaIris-setosa
5,4.8,7.9,1.0,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
6,4.9,13.7,3.2,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
7,5.0,18.4,4.3,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
8,5.1,15.5,3.6,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
9,5.2,8.3,1.9,Iris-setosaIris-setosaIris-setosaIris-versicolor
10,5.3,1.5,0.2,Iris-setosa
11,5.4,12.2,3.1,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
12,5.5,22.6,6.3,Iris-setosaIris-setosaIris-versicolorIris-vers...
13,5.6,25.2,8.5,Iris-versicolorIris-versicolorIris-versicolorI...
14,5.7,28.7,8.8,Iris-setosaIris-setosaIris-versicolorIris-vers...
15,5.8,28.5,9.8,Iris-setosaIris-versicolorIris-versicolorIris-...
16,5.9,14.1,5.1,Iris-versicolorIris-versicolorIris-virginica
17,6.0,27.9,9.0,Iris-versicolorIris-versicolorIris-versicolorI...
18,6.1,28.5,8.5,Iris-versicolorIris-versicolorIris-versicolorI...
19,6.2,19.0,6.9,Iris-versicolorIris-versicolorIris-virginicaIr...
20,6.3,46.2,16.3,Iris-versicolorIris-versicolorIris-versicolorI...
21,6.4,36.1,13.1,Iris-versicolorIris-versicolorIris-virginicaIr...
22,6.5,26.2,9.5,Iris-versicolorIris-virginicaIris-virginicaIri...
23,6.6,9.0,2.7,Iris-versicolorIris-versicolor
24,6.7,42.1,15.7,Iris-versicolorIris-versicolorIris-versicolorI...
25,6.8,16.2,5.8,Iris-versicolorIris-virginicaIris-virginica
26,6.9,21.1,8.2,Iris-versicolorIris-virginicaIris-virginicaIri...
27,7.0,4.7,1.4,Iris-versicolor
28,7.1,5.9,2.1,Iris-virginica
29,7.2,17.9,5.9,Iris-virginicaIris-virginicaIris-virginica
30,7.3,6.3,1.8,Iris-virginica
31,7.4,6.1,1.9,Iris-virginica
32,7.6,6.6,2.1,Iris-virginica
33,7.7,26.4,8.8,Iris-virginicaIris-virginicaIris-virginicaIris...
34,7.9,6.4,2.0,Iris-virginica

(df_1920.groupby('team')[['Total_pts','Total_reb','Total_ast']].
            .sort_values(by=(['Total_pts','Total_reb','Total_ast']),
            ascending=[0,0,1]).head())

In [249]:
Df_iris.Name.value_counts().axes

[Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object', name='Name')]

In [250]:
# basic stats, min, max, mean, std ...



Df_iris.describe(percentiles=[0.05,0.25,0.75,0.95,0.99],include='all')

        SepalLength  SepalWidth  PetalLength  PetalWidth         Name
count    150.000000  150.000000   150.000000  150.000000          150
unique          NaN         NaN          NaN         NaN            3
top             NaN         NaN          NaN         NaN  Iris-setosa
freq            NaN         NaN          NaN         NaN           50
mean       5.843333    3.054000     3.758667    1.198667          NaN
std        0.828066    0.433594     1.764420    0.763161          NaN
min        4.300000    2.000000     1.000000    0.100000          NaN
5%         4.600000    2.345000     1.300000    0.200000          NaN
25%        5.100000    2.800000     1.600000    0.300000          NaN
50%        5.800000    3.000000     4.350000    1.300000          NaN
75%        6.400000    3.300000     5.100000    1.800000          NaN
95%        7.255000    3.800000     6.100000    2.300000          NaN
99%        7.700000    4.151000     6.700000    2.500000          NaN
max        7.900000    4.400000     6.900000    2.500000          NaN

In [251]:
Df_iris.describe(percentiles=[0.05,0.25,0.75,0.95,0.99],include='O')

               Name
count           150
unique            3
top     Iris-setosa
freq             50

In [252]:
Df_iris['Name'].tolist()

['Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica']

In [253]:
result_iris=Df_iris.columns
result_iris

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

In [254]:
print(Df_iris.columns.tolist())

['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name']


https://saturncloud.io/blog/how-to-get-a-list-from-a-pandas-dataframe-column/

How to Get a List from a Pandas Dataframe Column
As a data scientist or software engineer you may often need to extract a list of values from a specific column of a Pandas dataframe This is a common task in data analysis and machine learning and can be easily accomplished using a few lines of code in Python

## 5. Get all statistics about a DataFrame

In [255]:
# show all columns stats
Df_iris.describe(include='all')

        SepalLength  SepalWidth  PetalLength  PetalWidth         Name
count    150.000000  150.000000   150.000000  150.000000          150
unique          NaN         NaN          NaN         NaN            3
top             NaN         NaN          NaN         NaN  Iris-setosa
freq            NaN         NaN          NaN         NaN           50
mean       5.843333    3.054000     3.758667    1.198667          NaN
std        0.828066    0.433594     1.764420    0.763161          NaN
min        4.300000    2.000000     1.000000    0.100000          NaN
25%        5.100000    2.800000     1.600000    0.300000          NaN
50%        5.800000    3.000000     4.350000    1.300000          NaN
75%        6.400000    3.300000     5.100000    1.800000          NaN
max        7.900000    4.400000     6.900000    2.500000          NaN

## 6. Select multiple columns by column name of a DataFrame

In [256]:
# select 'SepalLength','SepalWidth','Name'

In [257]:
result_iris=Df_iris.columns
result_iris

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

In [258]:
Df_iris.index[0]

0

In [259]:


#df_hsi.at[df_hsi.index[4],'Open']
Df_iris[['SepalLength', 'SepalWidth', 'Name']]

     SepalLength  SepalWidth            Name
0            5.1         3.5     Iris-setosa
1            4.9         3.0     Iris-setosa
2            4.7         3.2     Iris-setosa
3            4.6         3.1     Iris-setosa
4            5.0         3.6     Iris-setosa
..           ...         ...             ...
145          6.7         3.0  Iris-virginica
146          6.3         2.5  Iris-virginica
147          6.5         3.0  Iris-virginica
148          6.2         3.4  Iris-virginica
149          5.9         3.0  Iris-virginica

[150 rows x 3 columns]

## 7. Select multiple columns by index of a DataFrame

In [260]:
# select df all rows from column [0,1,4]
Df_iris.iloc[:,[0,1,4]]


# first 2 rows of [0,1,4] columns
#Df_iris.iloc[:,[0,1,4]]  #前面Row 後面Columns
#Df_iris.iloc[[0,1,2,4],[0,1,4]]

     SepalLength  SepalWidth            Name
0            5.1         3.5     Iris-setosa
1            4.9         3.0     Iris-setosa
2            4.7         3.2     Iris-setosa
3            4.6         3.1     Iris-setosa
4            5.0         3.6     Iris-setosa
..           ...         ...             ...
145          6.7         3.0  Iris-virginica
146          6.3         2.5  Iris-virginica
147          6.5         3.0  Iris-virginica
148          6.2         3.4  Iris-virginica
149          5.9         3.0  Iris-virginica

[150 rows x 3 columns]

In [261]:
print(Df_iris.columns)

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

In [262]:
print(Df_iris.axes)

[RangeIndex(start=0, stop=150, step=1), Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')]

## 8. Select a subset of rows and columns of a DataFrame

In [263]:
# first 2 rows of [0,1,4] columns
Df_iris.iloc[0:2,[0,1,4]]  #前面Row 後面Columns


#Df_iris.iloc[[0:1],[0,1,4]]

   SepalLength  SepalWidth         Name
0          5.1         3.5  Iris-setosa
1          4.9         3.0  Iris-setosa

In [264]:
Df_iris.iloc[[0,1,2,4],[0,1,4]]  #前面Row 後面Columna

   SepalLength  SepalWidth         Name
0          5.1         3.5  Iris-setosa
1          4.9         3.0  Iris-setosa
2          4.7         3.2  Iris-setosa
4          5.0         3.6  Iris-setosa

In [265]:
# last 2 rows of [0,1,4] columns
Df_iris.iloc[-4:-2,[0,1,4]]

     SepalLength  SepalWidth            Name
146          6.3         2.5  Iris-virginica
147          6.5         3.0  Iris-virginica

In [266]:
Df_iris.iloc[:2,[0,1,4]]

   SepalLength  SepalWidth         Name
0          5.1         3.5  Iris-setosa
1          4.9         3.0  Iris-setosa

## 9. Filter a DataFrame by condition

In [267]:
# The most proper way is using .loc
# select all rows 'PetalLength' > 6.4


# This is also OK for simple condition without other function
# try select all rows 'PetalLength' > 6.4 using other method

In [268]:
Df_iris.loc[Df_iris['PetalLength']>6.4]

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
105          7.6         3.0          6.6         2.1  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica

In [269]:
Df_iris[Df_iris['PetalLength']>6.4]

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
105          7.6         3.0          6.6         2.1  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica

## 10. Filter a DataFrame by condition

In [270]:
# The quickest way is using indexed location
# use iloc to filter 'PetalLength' > 6.4

## 11. Sort a DataFrame by a column

In [271]:
# sort df by 'SepalLength' 
Df_iris.sort_values(by=['SepalLength'])

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
13           4.3         3.0          1.1         0.1     Iris-setosa
42           4.4         3.2          1.3         0.2     Iris-setosa
38           4.4         3.0          1.3         0.2     Iris-setosa
8            4.4         2.9          1.4         0.2     Iris-setosa
41           4.5         2.3          1.3         0.3     Iris-setosa
..           ...         ...          ...         ...             ...
122          7.7         2.8          6.7         2.0  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica

[150 rows x 5 columns]

## 12. Sort a DataFrame by multiple column

In [272]:
# sort 'SepalLength','SepalWidth', by desc and desc order, print first 10 rows
Df_iris.sort_values(by=['SepalLength','SepalWidth'],ascending=True).iloc[[1,2],[0,3]]


#.head(10)

    SepalLength  PetalWidth
8           4.4         0.2
38          4.4         0.2

In [273]:
(Df_iris.sort_values(by=['SepalLength','SepalWidth'],ascending=True)).iloc[-10:,:]
#Df_iris.iloc[:2,[0,1,4]]

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
125          7.2         3.2          6.0         1.8  Iris-virginica
109          7.2         3.6          6.1         2.5  Iris-virginica
107          7.3         2.9          6.3         1.8  Iris-virginica
130          7.4         2.8          6.1         1.9  Iris-virginica
105          7.6         3.0          6.6         2.1  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica

## 13. Group a DataFrame by a column and calculate mean 
Group DataFrame using a mapper or by a Series of columns

In [274]:
# return mean of 3 species' SepalLength	SepalWidth	PetalLength	PetalWidth
#Df_iris.mean()
Df_iris[['SepalLength','SepalWidth','PetalLength','PetalWidth']].mean().reset_index()

#Df_iris.isna()

         index         0
0  SepalLength  5.843333
1   SepalWidth  3.054000
2  PetalLength  3.758667
3   PetalWidth  1.198667

In [275]:
Df_iris.groupby('SepalLength')[['SepalWidth','PetalLength','PetalWidth']].agg('mean').reset_index()

    SepalLength  SepalWidth  PetalLength  PetalWidth
0           4.3    3.000000     1.100000    0.100000
1           4.4    3.033333     1.333333    0.200000
2           4.5    2.300000     1.300000    0.300000
3           4.6    3.325000     1.325000    0.225000
4           4.7    3.200000     1.450000    0.200000
5           4.8    3.180000     1.580000    0.200000
6           4.9    2.866667     2.283333    0.533333
7           5.0    3.120000     1.840000    0.430000
8           5.1    3.477778     1.722222    0.400000
9           5.2    3.425000     2.075000    0.475000
10          5.3    3.700000     1.500000    0.200000
11          5.4    3.550000     2.033333    0.516667
12          5.5    2.842857     3.228571    0.900000
13          5.6    2.816667     4.200000    1.416667
14          5.7    3.100000     3.587500    1.100000
15          5.8    2.885714     4.071429    1.400000
16          5.9    3.066667     4.700000    1.700000
17          6.0    2.733333     4.650000    1.500000
18          6.1    2.850000     4.750000    1.416667
19          6.2    2.825000     4.750000    1.725000
20          6.3    2.855556     5.133333    1.811111
21          6.4    2.957143     5.157143    1.871429
22          6.5    3.000000     5.240000    1.900000
23          6.6    2.950000     4.500000    1.350000
24          6.7    3.050000     5.262500    1.962500
25          6.8    3.000000     5.400000    1.933333
26          6.9    3.125000     5.275000    2.050000
27          7.0    3.200000     4.700000    1.400000
28          7.1    3.000000     5.900000    2.100000
29          7.2    3.266667     5.966667    1.966667
30          7.3    2.900000     6.300000    1.800000
31          7.4    2.800000     6.100000    1.900000
32          7.6    3.000000     6.600000    2.100000
33          7.7    3.050000     6.600000    2.200000
34          7.9    3.800000     6.400000    2.000000

In [276]:
Df_iris.notnull()

     SepalLength  SepalWidth  PetalLength  PetalWidth  Name
0           True        True         True        True  True
1           True        True         True        True  True
2           True        True         True        True  True
3           True        True         True        True  True
4           True        True         True        True  True
..           ...         ...          ...         ...   ...
145         True        True         True        True  True
146         True        True         True        True  True
147         True        True         True        True  True
148         True        True         True        True  True
149         True        True         True        True  True

[150 rows x 5 columns]

In [277]:
# SELECT state, count(name)
#FROM df
#GROUP BY state
#ORDER BY state
#df.groupby(["Company"])["MPG"].agg(['max','min','mean','count','std','median'])


Df_iris.groupby(['Name']).agg(['max','min','mean','count','std','median'])

                SepalLength                                    SepalWidth  \
                        max  min   mean count       std median        max
Name
Iris-setosa             5.8  4.3  5.006    50  0.352490    5.0        4.4
Iris-versicolor         7.0  4.9  5.936    50  0.516171    5.9        3.4
Iris-virginica          7.9  4.9  6.588    50  0.635880    6.5        3.8

                                   ... PetalLength                         \
                 min   mean count  ...        mean count       std median
Name                               ...
Iris-setosa      2.3  3.418    50  ...       1.464    50  0.173511   1.50
Iris-versicolor  2.0  2.770    50  ...       4.260    50  0.469911   4.35
Iris-virginica   2.2  2.974    50  ...       5.552    50  0.551895   5.55

                PetalWidth
                       max  min   mean count       std median
Name
Iris-setosa            0.6  0.1  0.244    50  0.107210    0.2
Iris-versicolor        1.8  1.0  1.326    50  0.197753    1.3
Iris-virginica         2.5  1.4  2.026    50  0.274650    2.0

[3 rows x 24 columns]

In [299]:
Df_iris.groupby(['Name'])[[('SepalLength'),('SepalWidth'),('PetalLength'),('PetalWidth')]].mean()

                 SepalLength  SepalWidth  PetalLength  PetalWidth
Name
Iris-setosa            5.006       3.418        1.464       0.244
Iris-versicolor        5.936       2.770        4.260       1.326
Iris-virginica         6.588       2.974        5.552       2.026

In [300]:
Df_iris.groupby(['Name'])[[('SepalLength'),('SepalWidth'),('PetalLength'),('PetalWidth')]].agg(['mean'])

                SepalLength SepalWidth PetalLength PetalWidth
                       mean       mean        mean       mean
Name
Iris-setosa           5.006      3.418       1.464      0.244
Iris-versicolor       5.936      2.770       4.260      1.326
Iris-virginica        6.588      2.974       5.552      2.026

In [301]:
Df_iris.groupby(['Name'])

In [281]:
# return median of 3 species' SepalLength	SepalWidth	PetalLength	PetalWidth

In [304]:
Df_iris.groupby(['Name'])[[('SepalLength'),('SepalWidth'),('PetalLength'),('PetalWidth')]].median().reset_index()

              Name  SepalLength  SepalWidth  PetalLength  PetalWidth
0      Iris-setosa          5.0         3.4         1.50         0.2
1  Iris-versicolor          5.9         2.8         4.35         1.3
2   Iris-virginica          6.5         3.0         5.55         2.0

In [306]:
Df_iris.groupby(['Name'])[[('SepalLength'),('SepalWidth'),('PetalLength'),('PetalWidth')]].std().reset_index()

              Name  SepalLength  SepalWidth  PetalLength  PetalWidth
0      Iris-setosa     0.352490    0.381024     0.173511    0.107210
1  Iris-versicolor     0.516171    0.313798     0.469911    0.197753
2   Iris-virginica     0.635880    0.322497     0.551895    0.274650

In [284]:
# return SD of 3 species' SepalLength	SepalWidth	PetalLength	PetalWidth

## 14. Add a new column to a DataFrame

In [285]:
# The most proper way, is to add column followed df.index
# use df.loc[df.index, 'Volume'] 
# np.pi * 'SepalWidth'**2 * 'PetalLength'
# df.sample(3)                                    
#loc 方法和 iloc 方法一样，可以索引 DataFrame 数据，一般是通过 
#data.loc[index, col] = value 来进行赋值，这里利用：来索引全部行再进行赋值。#

In [307]:
Df_iris.loc[Df_iris.index,'Volume']=np.pi*Df_iris['SepalWidth']**2*Df_iris['PetalLength']

In [308]:
Df_iris

,SepalLength,SepalWidth,PetalLength,PetalWidth,Name,Volume
0,5.1,3.5,1.4,0.2,Iris-setosa,53.878314
1,4.9,3.0,1.4,0.2,Iris-setosa,39.584067
2,4.7,3.2,1.3,0.2,Iris-setosa,41.820881
3,4.6,3.1,1.5,0.2,Iris-setosa,45.286058
4,5.0,3.6,1.4,0.2,Iris-setosa,57.001057
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,147.026536
146,6.3,2.5,5.0,1.9,Iris-virginica,98.174770
147,6.5,3.0,5.2,2.0,Iris-virginica,147.026536
148,6.2,3.4,5.4,2.3,Iris-virginica,196.110780
149,5.9,3.0,5.1,1.8,Iris-virginica,144.199103

## 15. Rename an existing column

In [288]:
# Rename 'Name' as 'Species'

## 16. Drop a column

In [289]:
#drop 'Volume'

## 17. Data cleaning - dropna, fillna
<pre>Given Input:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Elle'],
        'Salary': [50000, 70000, 60000, 90000, np.NaN]}
payroll = pd.DataFrame(data)

Requirement:
1. Drop NaN
2. Fill NaN with zero
3. Fill NaN with mean
4. Fill NaN with median</pre>

In [290]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Elle'],
        'Salary': [50000, 70000, 60000, 90000, np.NaN]}
#

In [291]:
# fill nan with mean

In [292]:
# fill nan with median

In [293]:
# use dropna

In [294]:
# fill nan with 0

## 18. Find the unique value and number of unique value
<pre>In Iris DF, find :
1. Unique Iris species names
2. How many kinds of species
3. How many sample in each species</pre>

In [309]:
Df_iris['Name'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [310]:
Df_iris.groupby(['Name']).agg(['count'])

                SepalLength SepalWidth PetalLength PetalWidth Volume
                      count      count       count      count  count
Name
Iris-setosa              50         50          50         50     50
Iris-versicolor          50         50          50         50     50
Iris-virginica           50         50          50         50     50

In [311]:
Df_iris['Name'].value_counts()

Name
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

## 19. Replace values in a DataFrame
<pre>Change the Species names in iris DF:
Given Input:
df = df.replace({'Iris-setosa': 'Setosa', 
            'Iris-versicolor': 'Versicolor',
           'Iris-virginica':'Virginica'})

Desired Output:
['Setosa', 'Versicolor', 'Virginica']</pre>

In [298]:
df = df.replace({'Iris-setosa': 'Setosa', 
            'Iris-versicolor': 'Versicolor',
           'Iris-virginica':'Virginica'})
# unique

NameError: name 'df' is not defined

In [ ]:
Df_iris['Name']=Df_iris['Name'].replace({'Iris-setosa': 'Setosa', 
            'Iris-versicolor': 'Versicolor',
           'Iris-virginica':'Virginica'})

## 20. Replace values where the condition is False
<pre>Let's assume a species is large if its SepalLength is bigger
than mean. Create a new column 'LargeSpecies' and fill with 
Boolean to identify if the species belong to LargeSpecies.

You may create a column to fill with False first.
$> df.loc[df.index, 'LargeSpecies'] = False
</pre>

In [ ]:
Df_iris['SepalLength'].mean()

In [ ]:
Df_iris.loc[Df_iris.index, 'LargeSpecies'] = False
Df_iris.sample(2)

In [ ]:
''' df['LargeSpecies'] = df['LargeSpecies'].where(
    df['SepalLength']<df['SepalLength'].mean(), True)
df.sample(5)
'''

In [ ]:



Df_iris['SepalLength'].mean()

In [ ]:
Df_iris[(Df_iris['SepalLength']<Df_iris['SepalLength'].mean())]

In [ ]:
Df_iris['LargeSpecies']=np.where( Df_iris['SepalLength']<Df_iris['SepalLength'].mean(), True, False)
Df_iris.sample(20)

## 21. Replace values where the condition is True
<pre>df.mask() is the opposite of df.where()
df.mask(cond, other) will replace value with other if cond is True.

Let's create another column
df.loc[df.index, 'SmallSpecies'] = False
Replace the Boolean to True if 'SepalLength' smaller and equal
to mean.
</pre>

In [ ]:
print(int(np.random.randint(3,15,size=1)))

In [ ]:
Df_iris.loc[Df_iris.index, 'SmallSpecies'] = 0

Df_iris['SmallSpecies']=Df_iris['SmallSpecies'].mask(Df_iris['SmallSpecies']<=Df_iris['SmallSpecies'].mean(),True)

Df_iris.sample(int(np.random.randint(3,15,size=1)))

In [ ]:
#Df_iris['SmallSpecies']

In [ ]:
# Double check. Add up the LargeSpecies(True) and SmallSpecies(True)

## 22. Fill values with numpy.where
<pre>Requirement:
1. Create new column 'SampleSize'
2. Fill it 'Large' if SepalLength > mean, else 'Small'.

Given Input:
Drop column 'LargeSpecies' and 'SmallSpecies'
df = df.drop(['LargeSpecies','SmallSpecies'], axis=1)

Desired Output:

</pre>

In [ ]:
Df_iris = Df_iris.drop(['LargeSpecies','SmallSpecies'], axis=1)
Df_iris.sample(2)

In [ ]:
df['SampleSize'].value_counts()

In [ ]:
df.sample(3)

In [ ]:

Df_iris.loc[Df_iris.index,'SamplesSize']=np.where(Df_iris['SepalLength']<Df_iris['SepalLength'].mean(),'Large','Small')
Df_iris.sample(20)


#Df_iris.loc[Df_iris.index, 'LargeSpecies'] = False
#Df_iris.sample(2)

# Fill it 'Large' if SepalLength > mean, else 'Small

#Df_iris['LargeSpecies']=np.where( Df_iris['SepalLength']<Df_iris['SepalLength'].mean(), True, False)
#Df_iris.sample(20)

In [ ]:
Df_iris['SamplesSize'].value_counts()

## 23. Change DataFrame column postion

In [ ]:
'Species', 'SepalLength', 'SepalWidth',
         'PetalLength', 'PetalWidth', 'SampleSize'

In [ ]:
Df_iris=Df_iris[['Name', 'SepalLength', 'SepalWidth',
         'PetalLength', 'PetalWidth', 'SamplesSize']]


#SepalLength	SepalWidth	PetalLength	PetalWidth	Name	LargeSpecies	SmallSpecies	SamplesSize

In [ ]:
Df_iris.sample(3)

## 24. Apply a function on a column
Let's change the data in SampleSize field to Uppercase

In [ ]:
Df_iris['SampleSize'] =Df_iris['SampleSize'].apply(lambda x: x.upper())

In [ ]:
Df_iris.sample(5)

In [ ]:
Df_iris.head(5)

In [ ]:
def uppercase(x): 
     return x.upper()

Df_iris['SamplesSize'].apply(uppercase)

## 25. Map dict or function on a column

In [ ]:
Df_iris['SampleSize'] = Df_iris['SampleSize'].map({'SMALL': 'Small Iris', 
                                         'LARGE': 'Large Iris'})

df.sample(5)

In [ ]:
Df_iris['SamplesSize']=Df_iris['SamplesSize'].map({'SMALL':'Small Iris','LARGE':'Large Iris'})

Df_iris.sample(5)

## 26. Map a function on multiple column or whole DF

In [ ]:
Df_iris[['SepalLength','SepalWidth','PetalLength','PetalWidth']] = Df_iris[[
    'SepalLength','SepalWidth','PetalLength','PetalWidth']].map(lambda x: str(x) )

In [ ]:
Df_iris.sample(5)

In [ ]:
Falon_Dog=pd.DataFrame( { 'num_legs':[2,4,4,6],'num_wings':[2,0,0,0]}, index=['falon','dog','cat','ant'])
Falon_Dog

In [ ]:
Falon_Dog.value_counts()

In [ ]:

Falon_Dog.value_counts().to_frame()

In [ ]:
#df.groupby(["Company"])["MPG"].agg(['max','min','mean','count','std','median'])  
#Df_iris.groupby(['Name'])[[('SepalLength'),('SepalWidth'),('PetalLength'),('PetalWidth')]].mean()

#Falon_Dog.groupby(['num_legs'])['num_wings'].agg(['mean'])
Falon_Dog.groupby(['num_legs'])['num_wings']