In [2]:
import numpy as np
import pandas as pd

## 46. Create Datetime Series and index with Datetime series
<pre>
Requirement:
1. Create Datetime series idx :
            [four consecutive days] with dtype=datetime64[ns]
            from 2023-01-01 to 2023-01-04
2. Create Datetime series idxy based on idx' year, index with idx
3. Create Datetime series idxm based on idx' month, index with idx            
4. Create Datetime series idxd based on idx' day, index with idx           
</pre>

In [25]:
idx =pd.Series(pd.date_range(start='2023-01-01', periods=4,freq='D'))
#idxCreate Datetime Series and index with Datetime series
idx

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
dtype: datetime64[ns]

In [4]:
#dt.year

In [27]:
idxy = idx.dt.year
idxy.index=idx
idxy

2023-01-01    2023
2023-01-02    2023
2023-01-03    2023
2023-01-04    2023
dtype: int32

In [28]:
idxm = idx.dt.month
idxm.index=idx
idxm

2023-01-01    1
2023-01-02    1
2023-01-03    1
2023-01-04    1
dtype: int32

In [29]:
idxd = idx.dt.day
idxd.index=idx
idxd

2023-01-01    1
2023-01-02    2
2023-01-03    3
2023-01-04    4
dtype: int32

## 47. Create series with dtype and index with Datetime series
<pre>
Requirement:
1. Create series s1 [1, 2, 3, 4] 
                with dtype='int32', index with idx
2. Create series s2 [5., 6., 7., 8.] 
                with dtype='float32', index with idx</pre>

In [30]:

s1=pd.Series([1,2,3,4],dtype='int32',index=idx)

In [31]:

s2=pd.Series([5,6,7,8],dtype='float32',index=idx)

## 48. Create series with dtype and index with Datetime series
<pre>
Requirement:
1. Create series s3 ['On','Off','On', 'Off'] 
                    with dtype='category', index with idx
2. Create series s4 ['Alex','Bob','Chris','David'] 
                    with dtype='object', index with idx
</pre>

In [10]:

s3=pd.Series(['On','Off','On','Off'],dtype='category', index=idx)
s3

2023-01-01     On
2023-01-02    Off
2023-01-03     On
2023-01-04    Off
dtype: category
Categories (2, object): ['Off', 'On']

In [32]:

s4=pd.Series(['Akex','Bob','Chris','David'],dtype=object, index=idx)
print(s4)
print(type(s4))

2023-01-01     Akex
2023-01-02      Bob
2023-01-03    Chris
2023-01-04    David
dtype: object
<class 'pandas.core.series.Series'>

## 49. Combine Series into DataFrame
<pre>Column and Series, respectively as follow:
'year':idxy,
'month':idxm,
'day':idxd,
'name':s4,
'sales':s1,
'income':s2,
'desktop':s3,
</pre>

In [33]:
BoD=pd.DataFrame(data={'year':idxy,
'month':idxm,
'day':idxd,
'name':s4,
'sales':s1,
'income':s2,
'desktop':s3,
                      })


BoD

            year  month  day   name  sales  income desktop
2023-01-01  2023      1    1   Akex      1     5.0      On
2023-01-02  2023      1    2    Bob      2     6.0     Off
2023-01-03  2023      1    3  Chris      3     7.0      On
2023-01-04  2023      1    4  David      4     8.0     Off

In [34]:
BoD.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2023-01-01 to 2023-01-04
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     4 non-null      int32
 1   month    4 non-null      int32
 2   day      4 non-null      int32
 3   name     4 non-null      object
 4   sales    4 non-null      int32
 5   income   4 non-null      float32
 6   desktop  4 non-null      category
dtypes: category(1), float32(1), int32(4), object(1)
memory usage: 272.0+ bytes

## 50. Add new column with value by np.where
<pre>Requirement:
1. Add a new column 'bonus' to the df
2. Caluculate the bonus if sales>=3, bonus=income*0.3
                        else bonus=0
</pre>

In [35]:
BoD['bouns']=np.where(BoD['sales']>3,BoD['income']*0.3,0)

In [15]:
BoD

            year  month  day   name  sales  income desktop  bouns
2023-01-01  2023      1    1   Akex      1     5.0      On    0.0
2023-01-02  2023      1    2    Bob      2     6.0     Off    0.0
2023-01-03  2023      1    3  Chris      3     7.0      On    0.0
2023-01-04  2023      1    4  David      4     8.0     Off    2.4

## 51. Zip column and calculation
<pre>Requirement:
Generate a salary list, name with income+bonus

Desired Output:
[('Alex', 5.0),
 ('Bob', 6.0),
 ('Chris', 9.100000381469727),
 ('David', 10.399999618530273)]
</pre>

In [16]:
salary=list(zip(BoD['name'],BoD['income']+BoD['bouns']))
print(salary)

[('Akex', 5.0), ('Bob', 6.0), ('Chris', 7.0), ('David', 10.399999618530273)]

In [17]:
# hint: use zip and list
salary

[('Akex', 5.0), ('Bob', 6.0), ('Chris', 7.0), ('David', 10.399999618530273)]

## 52. Filter and manipulate DF 
<pre>Given Input:
salary = pd.DataFrame(data={'Name':df.name,
             'TotalIncome':df.income+df.bonus})

Requirement:
1. Find out the average salary
2. Total amount the company should prepare for payroll
3. Find out the highest performer (highest income)
4. Find out the standard diviation of the salary

In [18]:
salaryC_C=pd.DataFrame(data={'Name':BoD.name,
             'TotalIncome':BoD.income+BoD.bouns})
salaryC_C

             Name  TotalIncome
2023-01-01   Akex          5.0
2023-01-02    Bob          6.0
2023-01-03  Chris          7.0
2023-01-04  David         10.4

In [19]:
# average total salary
salaryC_C.loc[:,'TotalIncome'].mean()

7.1

In [20]:
# Amount for payroll
salaryC_C.loc[:,'TotalIncome'].sum()

28.4

In [21]:
# highest income name   (shall be 'David')

In [22]:
salaryC_C['Name'].loc[salaryC_C['TotalIncome'].idxmax()]

'David'

In [23]:


salaryC_C.TotalIncome.max()

10.4

In [24]:
max_max=salaryC_C.loc[ldxl]

max_max

NameError: name 'ldxl' is not defined

In [ ]:
# TotalIncome Standard Deviation
salaryC_C['TotalIncome'].std()

## 53. Series str
<pre>IT department need to create email account for
everyone, the email will be name + @abc.com
create a column 'email' and fill the email for every one.
The email should not include capital letter.
</pre>

In [ ]:
BoD['email']=BoD['name'].apply(str.lower)+'@abc.com'
BoD

## 54. Query and Search string
<pre>Find the following data:
1. sales smaller and equal 2 and desktop is "Off"
2. name start with 'A'
</pre>

## 55. Series Self Transform
<pre>The company want to increase basic income.
For income smaller than 7, raise 5%, else raise 3%.
Modify the income column with above condition.
</pre>

In [ ]:
BoD['Income']=Bob['Income'].apply(lambda x:x*1.05
                                                  if x<7
                                                  else x*1.03       )

In [ ]:
BoD

## 56. Rename column
<pre>Rename the following column:
desktop to laptop
income to basicSalary
</pre>

In [ ]:
BoD=BoD.rename(columns={'desktop':'laptop',
                   'income':'basicSalary'})

BoD

## 57. Assign new columns to DataFrame
<pre>Use df.assign() function to add new column 'totalSalary'
that equal to basicSalary plus bonus.
</pre>

In [ ]:
BoD.assign(totalSalary=BoD['basicSalary']+BoD['bonus'])
BoD

In [ ]:

df

## 58. Manipulate categoric data
<pre>Find out:
1. unique data in 'laptop'
2. number of unique data in 'laptop'
3. how many count in each unique data</pre>

## 59. Create categoric data column with others values
<pre>Creaet new column 'role' and classify employee role in 3 classes
by 'basicSalary'. 
below 6 is Junior, 
below 8 is Senior, 
above 8 is Manager.
Hint: use pd.cut()
</pre>

In [ ]:
# use pd.cut

## 60. Create categoric data column with quantile classes
<pre>Use pd.qcut to classify the 'totalSalary' in 
"Low Income", "Medium Income", "High Income", which base on 
'totalSalary' quantile.
Create new column named 'salaryClass'.
</pre>

In [ ]:
# use pd.qcut

## 61. Evaluate a Python expression as a string using various backends.
<pre>Create a temp column 'ExpectedAnnualSalary' to calculate
expected full year salary which is totalSalary x 13
</pre>

In [ ]:
# use pd.eval()

In [ ]:
df